name: Format

on: [push, pull_request]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Run Pint
              uses: aglipanci/laravel-pint-action@2.0.0
              with:
                preset: laravel
                configPath: "pint.json"

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Fix styling
